package com.mobdeve.s14.group24.everyday;

public enum
Keys {
    KEY_ID,
    KEY_DATE,
    KEY_IMAGE_PATH,
    KEY_CAPTION,
    KEY_MOOD,
    KEY_DESCENDING,
    MODIFIED_DATA_SET,
    INSERTED_DATA_SET,
    DELETED_DATA_SET,
    CUR_DATA_SET_POS,
    INITIALIZED_TABLE,
    NOTIFICATION_CHANNEL_ID,
    NOTIFICATION_CHANNEL_NAME,
    PROGRESS_MESSAGE,
    PROGRESS_VALUE
    }
